version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: DOCKERFILE
    container_name: prisma-postgres-api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/todo?schema=public"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: always
  
  

  
volumes:
  postgres-data: